### ISSUE TITLE
Cannot set Main LED's Blue

### ISSUE THREAD

**Issue by yaliv** [andreldm/harpoond#6] opened 2021-05-30 01:41 UTC
I tried to change the Main LED's Blue, e.g. to `0xff`, but doesn't work.
It's the same with wired or dongle mode.
The Red and Green combinations works though.

Is it one of the ignored values or is it just my mouse?
I just bought it yesterday.

**Comment by andreldm** [comment] 2021-06-01 23:29
Have you tried a slightly different value, e.g. `0xee`?

I'm unable to test the Main LED right now, my solution was to stick insulating tape over the LED to disable it, no need to run this daemon anymore for me :slightly_smiling_face:

> I just bought it yesterday.

If possible, return it. This mouse sucks, the dongle is super unreliable (I have a 10+ yrs old logitech that's much better). It started to display double click after few months of moderate use. Not to mention the inability to save settings to its internal memory. For me this was my first and last Corsair mouse. I didn't return it because I bought it while traveling abroad.

**Comment by yaliv** [comment] 2021-06-02 10:25
> Have you tried a slightly different value, e.g. 0xee?

Yes, I've tried different values. Still no effect :man_shrugging:

> my solution was to stick insulating tape over the LED to disable it

It's not about the battery life then :grin:

> Not to mention the inability to save settings to its internal memory.

OK, that's the worst part.
Maybe there's no internal memory at all in this product, even when using iCUE software, everything is saved in the software side.
Clearly I bought a wrong product :disappointed:

**Comment by andreldm** [comment] 2021-06-13 22:23
Fixed in a2332a1, silly mistake :slightly_frowning_face:

> It's not about the battery life then :grin:

This never was my need, the wireless dongle is too unreliable for serious usage.

> Maybe there's no internal memory at all in this product, even when using iCUE software, everything is saved in the software side.

Even if the mouse misses non-volatile memory, it doesn't explain why the heck iCUE has to be running in the background to send the keep alive packet every minute, makes me think this is by design so iCUE can spy on users.

> Clearly I bought a wrong product :disappointed:

Same feeling here.

**Closed as completed by andreldm** 2021-06-13 22:23 UTC
